services:
  notion-quest-frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    environment:
      - BACKEND_UPSTREAM=notion-quest-backend:8081
    depends_on:
      - notion-quest-backend

  notion-quest-backend:
    build: ./backend
    ports:
      - "8081:8081"

  notion-quest-tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
